"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { FolderKanban, KeyRound, Pencil, Plus, Save, Trash2, UserRound, X } from "lucide-react";
import MemberInsights from "@/components/MemberInsights";

type Profile = { id: number; email: string; name: string; avatar: string; title: string; bio: string; tags: string[] | null; github: string; linkedin: string; website: string; lang: string; created_at: string };
type Project = { id: number; title: string; summary: string; description: string; image_url: string; project_url: string; github_url: string; tags: string[] | null };
type ProjectForm = { title: string; summary: string; description: string; image_url: string; project_url: string; github_url: string; tags: string };
const emptyProject: ProjectForm = { title: "", summary: "", description: "", image_url: "", project_url: "", github_url: "", tags: "" };

function Modal({ title, children, close }: { title: string; children: React.ReactNode; close: () => void }) {
  return <div className="fixed inset-0 z-50 flex items-center justify-center p-4"><button aria-label="Close modal" onClick={close} className="absolute inset-0 bg-slate-950/30 backdrop-blur-sm" /><div className="relative max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl border border-slate-200 bg-white shadow-2xl"><div className="sticky top-0 flex items-center justify-between border-b border-slate-100 bg-white/95 px-6 py-4 backdrop-blur"><h2 className="font-mono text-sm font-bold text-slate-900">{title}</h2><button onClick={close} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100 hover:text-slate-700"><X size={18} /></button></div><div className="p-6">{children}</div></div></div>;
}

const inputStyle = "w-full rounded-lg border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm text-slate-900 outline-none transition focus:border-blue-400 focus:bg-white";
const Label = ({ children }: { children: React.ReactNode }) => <label className="mb-1.5 block font-mono text-[11px] font-semibold uppercase tracking-wide text-slate-500">{children}</label>;

export default function MemberPage() {
  const [profile, setProfile] = useState<Profile | null>(null);
  const [projects, setProjects] = useState<Project[]>([]);
  const [loading, setLoading] = useState(true);
  const [notice, setNotice] = useState("");
  const [modal, setModal] = useState<"profile" | "password" | "project" | null>(null);
  const [profileForm, setProfileForm] = useState<Record<string, string>>({});
  const [projectForm, setProjectForm] = useState<ProjectForm>(emptyProject);
  const [editingProject, setEditingProject] = useState<number | null>(null);

  async function load() {
    const [profileResponse, projectResponse] = await Promise.all([fetch("/api/profile"), fetch("/api/projects")]);
    if (!profileResponse.ok) { window.location.href = "/login"; return; }
    const profileData = await profileResponse.json(); const projectData = await projectResponse.json();
    setProfile(profileData.member); setProfileForm({ ...profileData.member, tags: profileData.member.tags?.join(", ") ?? "" });
    setProjects((projectData.projects ?? []).filter((item: { user_id: number }) => item.user_id === profileData.member.id)); setLoading(false);
  }
  useEffect(() => { load().catch(() => window.location.href = "/login"); }, []);
  function updateProfileField(field: string, value: string) { setProfileForm((form) => ({ ...form, [field]: value })); }
  function updateProjectField(field: keyof ProjectForm, value: string) { setProjectForm((form) => ({ ...form, [field]: value })); }
  function closeModal() { setModal(null); setEditingProject(null); setProjectForm(emptyProject); }
  async function saveProfile(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/profile", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...profileForm, tags: profileForm.tags.split(",").map((tag) => tag.trim()).filter(Boolean) }) }); const data = await response.json(); if (response.ok) { setProfile(data.member); setNotice("Profile saved successfully."); setModal(null); } else setNotice(data.error ?? "Could not save profile."); }
  async function changePassword(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const response = await fetch("/api/auth/change-password", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ currentPassword: data.get("currentPassword"), newPassword: data.get("newPassword") }) }); const body = await response.json(); setNotice(response.ok ? "Password updated successfully." : body.error ?? "Could not update password."); if (response.ok) setModal(null); }
  async function saveProject(event: FormEvent) { event.preventDefault(); const response = await fetch(editingProject ? `/api/projects/${editingProject}` : "/api/projects", { method: editingProject ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...projectForm, tags: projectForm.tags.split(",").map((tag) => tag.trim()).filter(Boolean) }) }); const data = await response.json(); if (!response.ok) return setNotice(data.error ?? "Could not save project."); setNotice(editingProject ? "Project updated." : "Project published."); closeModal(); load(); }
  async function removeProject(id: number) { if (!window.confirm("Remove this project from the public showcase?")) return; await fetch(`/api/projects/${id}`, { method: "DELETE" }); setProjects((items) => items.filter((item) => item.id !== id)); setNotice("Project removed."); }
  function editProject(project: Project) { setEditingProject(project.id); setProjectForm({ ...project, tags: project.tags?.join(", ") ?? "" }); setModal("project"); }
  if (loading || !profile) return <div className="grid min-h-screen place-items-center font-mono text-sm text-slate-500">$ loading workspace...</div>;

  return <div className="min-h-screen bg-[#f8fafc]"><header className="border-b border-slate-200 bg-white/85 backdrop-blur"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-6"><Link href="/" className="font-mono text-lg font-bold text-slate-900"><span className="text-blue-500">&lt;</span>tech<span className="text-blue-600">_pals</span><span className="text-blue-500"> /&gt;</span></Link><div className="flex gap-3"><Link href="/projects" className="rounded-lg border border-slate-200 px-3 py-2 font-mono text-xs text-slate-600 hover:bg-slate-50">public projects</Link></div></div></header>
    <main className="mx-auto max-w-6xl px-6 py-10"><div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><span className="font-mono text-xs font-bold tracking-widest text-blue-600">[ MEMBER_WORKSPACE ]</span><h1 className="mt-2 text-3xl font-bold text-slate-900">Your corner of tech_pals.</h1><p className="mt-2 text-slate-600">Keep your profile fresh and publish the work you want the community to see.</p></div><button onClick={() => setModal("project")} className="inline-flex items-center justify-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 font-mono text-xs font-bold text-white shadow-sm hover:bg-blue-700"><Plus size={15} />new project</button></div>
    {notice && <div className="mb-6 flex items-center justify-between rounded-lg border border-blue-200 bg-blue-50 px-4 py-3 font-mono text-xs text-blue-700"><span>{notice}</span><button onClick={() => setNotice("")}><X size={14} /></button></div>}
    <MemberInsights profile={profile} projectCount={projects.length} />
    <div className="grid gap-6 lg:grid-cols-[280px_1fr]"><aside className="h-fit rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-full border border-blue-100 bg-blue-50 font-mono font-bold text-blue-700">{profile.avatar || profile.name.slice(0, 2).toUpperCase()}</div><div className="min-w-0"><p className="truncate font-bold text-slate-900">{profile.name}</p><p className="truncate font-mono text-xs text-slate-500">{profile.title || "Member"}</p></div></div><div className="my-5 border-t border-slate-100" /><dl className="space-y-3 font-mono text-xs"><div className="flex justify-between gap-3"><dt className="text-slate-400">PROJECTS</dt><dd className="font-bold text-slate-700">{projects.length}</dd></div><div><dt className="mb-1 text-slate-400">EMAIL</dt><dd className="break-all text-slate-600">{profile.email}</dd></div></dl><div className="mt-5 grid gap-2"><button onClick={() => setModal("profile")} className="inline-flex items-center justify-center gap-2 rounded-lg border border-slate-200 px-3 py-2.5 font-mono text-xs font-semibold text-slate-700 hover:bg-slate-50"><UserRound size={14} />edit profile</button><button onClick={() => setModal("password")} className="inline-flex items-center justify-center gap-2 rounded-lg border border-slate-200 px-3 py-2.5 font-mono text-xs font-semibold text-slate-700 hover:bg-slate-50"><KeyRound size={14} />change password</button></div></aside>
    <section className="rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-6 py-5"><div><h2 className="font-bold text-slate-900">Published projects</h2><p className="mt-1 text-sm text-slate-500">Projects shown on the public community page.</p></div><span className="rounded bg-slate-100 px-2 py-1 font-mono text-xs text-slate-500">{projects.length}</span></div>{projects.length === 0 ? <div className="p-12 text-center"><FolderKanban className="mx-auto mb-3 text-blue-400" size={32} /><p className="font-mono text-sm text-slate-500">No projects yet. Add your first one when you’re ready.</p></div> : <div className="divide-y divide-slate-100">{projects.map((project) => <article key={project.id} className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><h3 className="font-bold text-slate-900">{project.title}</h3><p className="mt-1 truncate text-sm text-slate-500">{project.summary || project.description || "No summary added."}</p><div className="mt-2 flex flex-wrap gap-1">{project.tags?.map((tag) => <span key={tag} className="rounded bg-blue-50 px-2 py-0.5 font-mono text-[10px] text-blue-700">{tag}</span>)}</div></div><div className="flex shrink-0 gap-2"><button onClick={() => editProject(project)} className="rounded-lg border border-slate-200 p-2 text-slate-500 hover:bg-slate-50 hover:text-blue-600" aria-label="Edit project"><Pencil size={15} /></button><button onClick={() => removeProject(project.id)} className="rounded-lg border border-red-100 p-2 text-red-500 hover:bg-red-50" aria-label="Remove project"><Trash2 size={15} /></button></div></article>)}</div>}</section></div></main>
    {modal === "profile" && <Modal title="Edit profile" close={closeModal}><form onSubmit={saveProfile} className="grid gap-4 sm:grid-cols-2"><div><Label>Name</Label><input required value={profileForm.name ?? ""} onChange={(e) => updateProfileField("name", e.target.value)} className={inputStyle} /></div><div><Label>Initials / avatar</Label><input value={profileForm.avatar ?? ""} onChange={(e) => updateProfileField("avatar", e.target.value)} className={inputStyle} /></div><div><Label>Role title</Label><input value={profileForm.title ?? ""} onChange={(e) => updateProfileField("title", e.target.value)} className={inputStyle} /></div><div><Label>Primary language</Label><input value={profileForm.lang ?? ""} onChange={(e) => updateProfileField("lang", e.target.value)} className={inputStyle} /></div><div className="sm:col-span-2"><Label>Bio</Label><textarea rows={3} value={profileForm.bio ?? ""} onChange={(e) => updateProfileField("bio", e.target.value)} className={inputStyle} /></div><div className="sm:col-span-2"><Label>Skills (comma separated)</Label><input value={profileForm.tags ?? ""} onChange={(e) => updateProfileField("tags", e.target.value)} className={inputStyle} /></div><div><Label>GitHub URL</Label><input value={profileForm.github ?? ""} onChange={(e) => updateProfileField("github", e.target.value)} className={inputStyle} /></div><div><Label>LinkedIn URL</Label><input value={profileForm.linkedin ?? ""} onChange={(e) => updateProfileField("linkedin", e.target.value)} className={inputStyle} /></div><div className="sm:col-span-2"><Label>Website URL</Label><input value={profileForm.website ?? ""} onChange={(e) => updateProfileField("website", e.target.value)} className={inputStyle} /></div><div className="sm:col-span-2 flex justify-end gap-3 border-t border-slate-100 pt-4"><button type="button" onClick={closeModal} className="rounded-lg px-4 py-2 font-mono text-xs text-slate-600 hover:bg-slate-50">cancel</button><button className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2 font-mono text-xs font-bold text-white hover:bg-blue-700"><Save size={14} />save changes</button></div></form></Modal>}
    {modal === "password" && <Modal title="Change password" close={closeModal}><form onSubmit={changePassword} className="space-y-4"><div><Label>Current password</Label><input name="currentPassword" required type="password" className={inputStyle} /></div><div><Label>New password</Label><input name="newPassword" required minLength={8} type="password" className={inputStyle} /><p className="mt-2 text-xs text-slate-500">Use at least eight characters.</p></div><div className="flex justify-end gap-3 border-t border-slate-100 pt-4"><button type="button" onClick={closeModal} className="rounded-lg px-4 py-2 font-mono text-xs text-slate-600">cancel</button><button className="rounded-lg bg-blue-600 px-4 py-2 font-mono text-xs font-bold text-white hover:bg-blue-700">update password</button></div></form></Modal>}
    {modal === "project" && <Modal title={editingProject ? "Edit project" : "Add project"} close={closeModal}><form onSubmit={saveProject} className="grid gap-4 sm:grid-cols-2"><div><Label>Project title *</Label><input required value={projectForm.title} onChange={(e) => updateProjectField("title", e.target.value)} className={inputStyle} /></div><div><Label>Short summary</Label><input value={projectForm.summary} onChange={(e) => updateProjectField("summary", e.target.value)} className={inputStyle} /></div><div><Label>Live project URL</Label><input value={projectForm.project_url} onChange={(e) => updateProjectField("project_url", e.target.value)} className={inputStyle} /></div><div><Label>GitHub URL</Label><input value={projectForm.github_url} onChange={(e) => updateProjectField("github_url", e.target.value)} className={inputStyle} /></div><div className="sm:col-span-2"><Label>Project image URL</Label><input value={projectForm.image_url} onChange={(e) => updateProjectField("image_url", e.target.value)} className={inputStyle} /></div><div className="sm:col-span-2"><Label>Tags (comma separated)</Label><input value={projectForm.tags} onChange={(e) => updateProjectField("tags", e.target.value)} className={inputStyle} /></div><div className="sm:col-span-2"><Label>Description</Label><textarea rows={4} value={projectForm.description} onChange={(e) => updateProjectField("description", e.target.value)} className={inputStyle} /></div><div className="sm:col-span-2 flex justify-end gap-3 border-t border-slate-100 pt-4"><button type="button" onClick={closeModal} className="rounded-lg px-4 py-2 font-mono text-xs text-slate-600">cancel</button><button className="rounded-lg bg-blue-600 px-4 py-2 font-mono text-xs font-bold text-white hover:bg-blue-700">{editingProject ? "save project" : "publish project"}</button></div></form></Modal>}
  </div>;
}
