import { CalendarDays, CheckCircle2, Circle, FolderKanban, Github, Globe, Linkedin } from "lucide-react";

type Profile = { name: string; avatar: string; title: string; bio: string; tags: string[] | null; github: string; linkedin: string; website: string; lang: string; created_at: string };

export default function MemberInsights({ profile, projectCount }: { profile: Profile; projectCount: number }) {
  const checks = [
    ["Profile name and avatar", Boolean(profile.name && profile.avatar)],
    ["Role and short bio", Boolean(profile.title && profile.bio)],
    ["Skills and main language", Boolean(profile.tags?.length && profile.lang)],
    ["At least one social link", Boolean(profile.github || profile.linkedin || profile.website)],
    ["Published project", projectCount > 0],
  ];
  const complete = checks.filter(([, value]) => value).length;
  const percentage = Math.round((complete / checks.length) * 100);
  return <section className="mb-6 grid gap-4 lg:grid-cols-[1.2fr_1fr]"><div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div><p className="font-mono text-[11px] font-bold tracking-widest text-blue-600">PROFILE_READINESS</p><h2 className="mt-2 font-bold text-slate-900">{percentage}% complete</h2></div><span className="rounded-lg bg-blue-50 px-2.5 py-1 font-mono text-xs font-bold text-blue-700">{complete}/{checks.length}</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600 transition-all" style={{ width: `${percentage}%` }} /></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{checks.map(([label, complete]) => <div key={String(label)} className="flex items-center gap-2 text-xs text-slate-600">{complete ? <CheckCircle2 size={14} className="shrink-0 text-cyan-600" /> : <Circle size={14} className="shrink-0 text-slate-300" />}{label}</div>)}</div></div><div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><p className="font-mono text-[11px] font-bold tracking-widest text-blue-600">ACCOUNT_ACTIVITY</p><div className="mt-4 grid grid-cols-2 gap-4"><div className="rounded-lg bg-slate-50 p-3"><CalendarDays size={16} className="text-blue-500" /><p className="mt-2 font-mono text-[10px] text-slate-400">JOINED</p><p className="mt-1 text-sm font-semibold text-slate-700">{new Date(profile.created_at).toLocaleDateString()}</p></div><div className="rounded-lg bg-slate-50 p-3"><FolderKanban size={16} className="text-blue-500" /><p className="mt-2 font-mono text-[10px] text-slate-400">PUBLISHED</p><p className="mt-1 text-sm font-semibold text-slate-700">{projectCount} projects</p></div></div><div className="mt-4 flex items-center gap-3 border-t border-slate-100 pt-4">{profile.github ? <a href={profile.github} target="_blank" rel="noreferrer" aria-label="GitHub" className="text-slate-400 hover:text-blue-600"><Github size={16} /></a> : null}{profile.linkedin ? <a href={profile.linkedin} target="_blank" rel="noreferrer" aria-label="LinkedIn" className="text-slate-400 hover:text-blue-600"><Linkedin size={16} /></a> : null}{profile.website ? <a href={profile.website} target="_blank" rel="noreferrer" aria-label="Website" className="text-slate-400 hover:text-blue-600"><Globe size={16} /></a> : null}{!profile.github && !profile.linkedin && !profile.website ? <p className="text-xs text-slate-500">Add a social link to make your profile easier to discover.</p> : <p className="text-xs text-slate-500">Your public links are ready.</p>}</div></div></section>;
}
